apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: fatoubinetousarr06/frontend:v1  
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: frontend-config
